# Generated by Django 4.0.2 on 2022-02-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='image',
            field=models.ImageField(blank=True, default='default_g5kghd.jpg', null=True, upload_to='barber_image'),
        ),
    ]
